### ISSUE TITLE
glibc detected free() invalid pointer when constructing a polyhedron

### ISSUE THREAD

**Issue by Puttichai** [mcmtroffaes/pycddlib#7] opened 2015-06-30 03:49 UTC
Hi,

cdd.Polyhedron seems to have some problems when constructing polyhedron from some particular matrices (V-representation). Below is an example of such a matrix.

    import numpy as np
    import cdd

    R = np.array([[ -0.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,  -4.        ,
                    -4.        ,   4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,  -0.        ,  -4.        ,  -4.        ,
                     4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,
                    -4.        ,  -4.        ,   4.        ,   4.        ],
                  [ -0.        , -40.        , -40.        , -40.        , -40.        , -40.        , -40.        , -40.        , -40.        , -40.        ,
                   -40.        , -40.        , -40.        , -40.        , -40.        , -40.        , -40.        ,  -0.        ,  40.        ,  40.        ,
                    40.        ,  40.        ,  40.        ,  40.        ,  40.        ,  40.        ,  40.        ,  40.        ,  40.        ,  40.        ,
                    40.        ,  40.        ,  40.        ,  40.        ],
                  [ -0.        ,   4.        ,  -4.        ,   4.        ,  -4.        ,   4.        ,  -4.        ,   4.        ,  -4.        ,   4.        ,
                    -4.        ,   4.        ,  -4.        ,   4.        ,  -4.        ,   4.        ,  -4.        ,  -0.        ,  -4.        ,   4.        ,
                    -4.        ,   4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,   4.        ,  -4.        ,  -4.        ,   4.        ,
                     4.        ,  -4.        ,  -4.        ,   4.        ],
                  [ -0.        ,  28.22314601,  30.19098601,  28.22314601,  30.19098601,  28.0999032 ,  30.0677432 ,  28.0999032 ,  30.0677432 ,  29.05601375,
                    31.02398625,  29.05601375,  31.02398625,  29.05601375,  31.02398625,  29.05601375,  31.02398625,  -0.        , -28.02714601, -30.38698601,
                   -28.02714601, -30.38698601, -30.2637432 , -27.9039032 , -27.9039032 , -30.2637432 , -31.21985375, -28.86014625, -28.86014625, -31.21985375,
                   -31.21985375, -28.86014625, -28.86014625, -31.21985375],
                  [ -0.        ,  -4.83120097,  -1.01021223,   1.01021223,   4.83120097,  -4.88536345,  -0.93140119,   0.93140119,   4.88536345,  -5.00096   ,
                    -1.00704   ,   1.00704   ,   5.00096   ,  -4.91296   ,  -1.09504   ,   1.09504   ,   4.91296   ,  -0.        ,  -1.01021223,  -4.83120097,
                     4.83120097,   1.01021223,  -4.88536345,  -0.93140119,   4.88536345,   0.93140119,  -5.00096   ,  -1.00704   ,   5.00096   ,   1.00704   ,
                    -4.91296   ,  -1.09504   ,   4.91296   ,   1.09504   ],
                  [ -0.        , -20.08886368, -20.08886368, -18.12102368, -18.12102368, -20.75373128, -20.75373128, -18.78589128, -18.78589128, -20.95358629,
                   -20.95358629, -18.98561378, -18.98561378, -20.07358622, -20.07358622, -18.10561371, -18.10561371,  -0.        ,  17.92502368,  17.92502368,
                    20.28486368,  20.28486368,  18.58989128,  18.58989128,  20.94973128,  20.94973128,  18.78974629,  18.78974629,  21.14945378,  21.14945378,
                    17.90974622,  17.90974622,  20.26945371,  20.26945371]])

    ## changing from span to face
    data_type = 1 # vertices

    V = np.hstack((np.tile(data_type, (R.shape[1], 1)), R.T))
    V_cdd = cdd.Matrix(V, number_type = 'float')
    V_cdd.rep_type = cdd.RepType.GENERATOR
    P = cdd.Polyhedron(V_cdd)

**Comment by mcmtroffaes** [comment] 2015-06-30 07:56
Thanks for reporting. I've reproduced the bug, investigating the code now...

**Comment by mcmtroffaes** [comment] 2015-06-30 08:43
So I've found the cause: cddlib fails to load your polyhedron due to numerical inconsistency of the input matrix.

     Error: Numerical inconsistency is found.  Use the GMP exact arithmetic.

The error handling code tries to clean up memory, but apparently cddlib has trouble clearing polyhedron data that results from inconsistent input. In the worst case I need to leave the memory dangling, but I'll try to see if I can fix this in cddlib itself.

**Comment by mcmtroffaes** [comment] 2015-06-30 09:19
This is now fixed on develop. I'll roll a new release as soon as I get appveyor set up properly.

**Closed by mcmtroffaes** 2015-06-30 09:19 UTC
