### ISSUE TITLE
Installation using pip on MacOS 11.6

### ISSUE THREAD

**Issue by stephane-caron** [mcmtroffaes/pycddlib#49] opened 2021-11-28 13:02 UTC
@alphaville reported the following issue with trying to install pycddlib on MacOS 11.6:

> I tried to install pypoman on MacOS v11.6 within a virtual environment with Python version 3.8.9. I started by installing cython and gplk using:
> ```
> brew install cython
> brew install gplk
> ```
> and then installed scipy with pip install scipy. However, pip install pypoman gives the following error
> ```
> $ pip install pypoman
> Collecting pypoman
>   Using cached pypoman-0.5.4-py3-none-any.whl
> Collecting pycddlib
>   Using cached pycddlib-2.1.4.tar.gz (265 kB)
>   Preparing metadata (setup.py) ... done
> Collecting cvxopt
>   Using cached cvxopt-1.2.7-cp38-cp38-macosx_10_9_x86_64.whl (3.1 MB)
> Building wheels for collected packages: pycddlib
>   Building wheel for pycddlib (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-wheel-6ht_j0yq
>        cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/
>   Complete output (29 lines):
>   /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
>     warnings.warn(
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
>       setup(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
>       _install_setup_requires(attrs)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
>       dist.fetch_build_eggs(dist.setup_requires)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
>       resolved_dists = pkg_resources.working_set.resolve(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
>       dist = best[req.key] = env.best_match(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
>       return self.obtain(req, installer)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
>       return installer(requirement)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
>       return fetch_build_egg(self, req)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
>       wheel.install_as_egg(dist_location)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
>       self._install_as_egg(destination_eggdir, zf)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
>       self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
>       os.mkdir(destination_eggdir)
>   FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
>   ----------------------------------------
>   ERROR: Failed building wheel for pycddlib
>   Running setup.py clean for pycddlib
>   ERROR: Command errored out with exit status 1:
>    command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
>        cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32
>   Complete output (29 lines):
>   /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
>     warnings.warn(
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
>       setup(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
>       _install_setup_requires(attrs)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
>       dist.fetch_build_eggs(dist.setup_requires)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
>       resolved_dists = pkg_resources.working_set.resolve(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
>       dist = best[req.key] = env.best_match(
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
>       return self.obtain(req, installer)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
>       return installer(requirement)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
>       return fetch_build_egg(self, req)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
>       wheel.install_as_egg(dist_location)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
>       self._install_as_egg(destination_eggdir, zf)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
>       self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
>     File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
>       os.mkdir(destination_eggdir)
>   FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
>   ----------------------------------------
>   ERROR: Failed cleaning build dir for pycddlib
> Failed to build pycddlib
> Installing collected packages: pycddlib, cvxopt, pypoman
>     Running setup.py install for pycddlib ... error
>     ERROR: Command errored out with exit status 1:
>      command: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-record-0zuwcfj8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/3054363/PycharmProjects/setz/venv/include/site/python3.8/pycddlib
>          cwd: /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/
>     Complete output (29 lines):
>     /Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
>       warnings.warn(
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py", line 107, in <module>
>         setup(
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup
>         _install_setup_requires(attrs)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires
>         dist.fetch_build_eggs(dist.setup_requires)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
>         resolved_dists = pkg_resources.working_set.resolve(
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
>         dist = best[req.key] = env.best_match(
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
>         return self.obtain(req, installer)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
>         return installer(requirement)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
>         return fetch_build_egg(self, req)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
>         wheel.install_as_egg(dist_location)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
>         self._install_as_egg(destination_eggdir, zf)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
>         self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
>       File "/Users/3054363/PycharmProjects/setz/venv/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
>         os.mkdir(destination_eggdir)
>     FileExistsError: [Errno 17] File exists: '/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/.eggs/Cython-0.29.24-py3.8-macosx-10.14-x86_64.egg'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /Users/3054363/PycharmProjects/setz/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"'; __file__='"'"'/private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-install-wf69f8bg/pycddlib_ee6ee3ac177c42c487f886b285492f32/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xf/r_jhy8wd01s9nr6zqnzh6f1xnv1_63/T/pip-record-0zuwcfj8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/3054363/PycharmProjects/setz/venv/include/site/python3.8/pycddlib Check the logs for full command output.
> ```

I'm not sure where this error comes from. Perhaps the pip mishap is due to Cython being installed via brew?

**Comment by stephane-caron** [comment] 2021-11-28 13:04
@alphaville This is just a check but I guess you get the same error with `pip install pycddlib` directly?

**Comment by mcmtroffaes** [comment] 2021-11-28 16:22
I'm very sorry to say that I don't have a mac myself for testing... but I'll try to help to the best of my ability.

From the logs it seems it doesn't even come around to trying to compile cddlib, whence it looks like a problem with Cython on macos. Do other packages that need Cython for building have the same problem?

**Comment by Edenharder** [comment] 2022-02-08 17:41
@mcmtroffaes I'm using Archlinux. There is a similar problem when I try to install pycddlib:
```
Collecting pycddlib
  Downloading pycddlib-2.1.4.tar.gz (265 kB)
     |████████████████████████████████| 265 kB 2.1 MB/s            
Building wheels for collected packages: pycddlib
  Building wheel for pycddlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-19q2slz4/pycddlib_f4a1caabff74493ca23ad533096e9b20/setup.py'"'"'; __file__='"'"'/tmp/pip-install-19q2slz4/pycddlib_f4a1caabff74493ca23ad533096e9b20/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hz4mdnk9
       cwd: /tmp/pip-install-19q2slz4/pycddlib_f4a1caabff74493ca23ad533096e9b20/
  Complete output (186 lines):
  /usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  running bdist_wheel
  running build
  running build_ext
  skipping 'cdd.c' Cython extension (up-to-date)
  building 'cdd' extension
  creating build
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/cddlib
  creating build/temp.linux-x86_64-3.10/cddlib/lib-src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/usr/include/python3.10 -c cdd.c -o build/temp.linux-x86_64-3.10/cdd.o
  cdd.c: In function ‘__pyx_f_3cdd_libc_stdio_tmpfile’:
  cdd.c:2425:3: warning: label ‘__pyx_L1_error’ defined but not used [-Wunused-label]
   2425 |   __pyx_L1_error:;
.....
.....
```

**Comment by mcmtroffaes** [comment] 2022-02-08 22:54
Thanks for chiming in but this looks like a different problem @Edenharder - need to see the full log to tell what's going on, but it's definitely further into the process compared to the macos problem. My guess is that you don't have the gmp development headers installed. If that doesn't fix the problem, feel free to post a separate issue, including the full logs if possible.

**Comment by Edenharder** [comment] 2022-02-09 13:59
@mcmtroffaes Thank you! I just opened a new issue.

**Comment by mcmtroffaes** [comment] 2022-02-09 16:45
@Edenharder FYI to keep things organized, I'll shortly remove this comment and the above comments that aren't related to the original macos issue (since everything from the archlinux problem is now in the new issue). I thought I give you some notice before I do so.

**Comment by mcmtroffaes** [comment] 2022-05-07 21:18
The release is now also getting tested against macos via github actions, and I'm glad to report that it's succeeding there. I think this may have been caused by the same issue that's causing #53 (although I'm not 100% sure).

**Comment by mcmtroffaes** [comment] 2022-05-08 15:10
Macos is now fully tested via github actions, and all seems to be working, so closing. I think it may have had something to do with Cython, and the 2.1.4 release including the generated Cython code, which I've now removed as it seems to cause compatibility issues across platforms. Feel free to reopen however if the issue still isn't resolved in your own testing.

**Closed by mcmtroffaes** 2022-05-08 15:10 UTC
